/**
 * Download TCGdex set symbols to public/images/symbols/{serieSlug}.png
 *
 * Input : scripts/_tcgdex-symbol-mapping.json (produced by build-tcgdex-symbol-mapping.ts)
 * Output: public/images/symbols/<serieSlug>.png
 *
 * Run: npx tsx scripts/download-set-symbols.ts
 */

import { readFileSync, mkdirSync, writeFileSync, existsSync } from 'node:fs';
import path from 'node:path';

type Mapping = {
  serieSlug: string;
  serieName: string;
  tcgdexSetId: string | null;
  symbolUrl: string | null;
};

const OUT_DIR = path.resolve('public/images/symbols');
const MAPPING_PATH = path.resolve('scripts/_tcgdex-symbol-mapping.json');
const SLUGS_FILE  = path.resolve('src/data/symbol-slugs.ts');

async function main() {
  if (!existsSync(MAPPING_PATH)) {
    console.error(`Mapping file not found: ${MAPPING_PATH}`);
    console.error('Run `npx tsx scripts/build-tcgdex-symbol-mapping.ts` first.');
    process.exit(1);
  }

  const raw = readFileSync(MAPPING_PATH, 'utf-8');
  const mappings: Mapping[] = JSON.parse(raw);

  mkdirSync(OUT_DIR, { recursive: true });

  let ok = 0;
  let skipped = 0;
  let failed = 0;
  const downloaded: string[] = [];

  for (const m of mappings) {
    if (!m.symbolUrl) {
      skipped++;
      continue;
    }
    const outPath = path.join(OUT_DIR, `${m.serieSlug}.png`);

    try {
      const res = await fetch(m.symbolUrl);
      if (!res.ok) {
        console.log(`  [${res.status}] ${m.serieSlug}  (${m.symbolUrl})`);
        failed++;
        continue;
      }
      const buffer = Buffer.from(await res.arrayBuffer());
      writeFileSync(outPath, buffer);
      ok++;
      downloaded.push(m.serieSlug);
      process.stdout.write(`  ok  ${m.serieSlug}\n`);
    } catch (e) {
      console.log(`  err  ${m.serieSlug}  ${e instanceof Error ? e.message : e}`);
      failed++;
    }
  }

  console.log(`\nDone: ${ok} downloaded, ${skipped} skipped (no URL), ${failed} failed`);

  // Emit a generated TS file so pages can cheaply check which series have a symbol.
  downloaded.sort();
  const tsSource =
    '// This file is auto-generated by scripts/download-set-symbols.ts — do not edit.\n' +
    `// Generated: ${new Date().toISOString()}\n` +
    '\n' +
    'export const SYMBOL_SLUGS: ReadonlySet<string> = new Set([\n' +
    downloaded.map((s) => `  '${s}',`).join('\n') +
    '\n]);\n';
  writeFileSync(SLUGS_FILE, tsSource);
  console.log(`Written: ${SLUGS_FILE}`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
