#!/usr/bin/env tsx
/**
 * Scan `public/images/items/*.jpg` and emit a `serieSlug → Set<TYPE>` map
 * as a static TS module the mobile client can import.
 *
 * File naming convention: `{serieSlug}-{typeSlug}.jpg` — identical to
 * what `getAvailableImageTypes()` reads server-side on the web build.
 */

import * as fs from "fs";
import * as path from "path";

const ROOT = path.resolve(__dirname, "..");
const DIR = path.join(ROOT, "public", "images", "items");
const OUT = path.join(ROOT, "src", "data", "item-images-map.generated.ts");

const TYPE_SLUG_REVERSE: Record<string, string> = {
  booster: "BOOSTER",
  duopack: "DUOPACK",
  tripack: "TRIPACK",
  blister: "BLISTER",
  "mini-tin": "MINI_TIN",
  "pokeball-tin": "POKEBALL_TIN",
  bundle: "BUNDLE",
  "box-set": "BOX_SET",
  etb: "ETB",
  "booster-box": "BOOSTER_BOX",
  upc: "UPC",
  tin: "TIN",
  "theme-deck": "THEME_DECK",
  "trainer-kit": "TRAINER_KIT",
};

// Ordered list of known type slugs, longest first — the filename parse
// must prefer multi-word slugs (e.g. "booster-box") before single words
// ("booster") so `arceus-booster-box.jpg` doesn't get misclassified as
// `arceus` + `booster-box` ✓ vs `arceus-booster` + `-box`.
const SLUGS_BY_LENGTH = Object.keys(TYPE_SLUG_REVERSE).sort(
  (a, b) => b.length - a.length,
);

function detect(file: string): { serieSlug: string; type: string } | null {
  if (!file.endsWith(".jpg")) return null;
  const stem = file.slice(0, -4);
  for (const typeSlug of SLUGS_BY_LENGTH) {
    const suffix = `-${typeSlug}`;
    if (stem.endsWith(suffix)) {
      return {
        serieSlug: stem.slice(0, -suffix.length),
        type: TYPE_SLUG_REVERSE[typeSlug],
      };
    }
  }
  return null;
}

const map: Record<string, Set<string>> = {};

const files = fs.readdirSync(DIR);
for (const file of files) {
  const hit = detect(file);
  if (!hit) continue;
  if (!map[hit.serieSlug]) map[hit.serieSlug] = new Set();
  map[hit.serieSlug].add(hit.type);
}

// Stable, deterministic output
const sortedSeries = Object.keys(map).sort();
const entries = sortedSeries.map((slug) => {
  const types = [...map[slug]].sort();
  return `  "${slug}": [${types.map((t) => `"${t}"`).join(", ")}],`;
});

const contents = `// AUTO-GENERATED by scripts/generate-item-images-map.ts
// Maps each serie slug to the list of ItemType keys that have a static
// artwork in \`public/images/items/\`. Imported by the mobile
// SerieProduitsClient to decide which generic product tiles render with
// a "real" image vs the "without image" fallback collapse — matches the
// server-side \`fs.readdirSync\` pass the web RSC runs.
//
// DO NOT EDIT BY HAND. Regenerate with \`npm run gen:item-images-map\`.

export const ITEM_IMAGES_BY_SERIE: Record<string, readonly string[]> = {
${entries.join("\n")}
};
`;

fs.writeFileSync(OUT, contents, "utf8");
console.log(
  `[gen:item-images-map] wrote ${sortedSeries.length} series / ${files.filter((f) => f.endsWith(".jpg")).length} images → ${path.relative(ROOT, OUT)}`,
);
