#!/usr/bin/env tsx
/**
 * Scan `public/images/items/*.{jpg,png}` and emit a `serieSlug → Set<TYPE>` map
 * plus a flat URL map that records the real extension on disk. Imported by
 * the mobile client (and by ItemImage) so we don't have to guess between
 * `.jpg` and `.png` after the rembg background-removal pass converts files.
 *
 * File naming convention: `{serieSlug}-{typeSlug}.{jpg|png}`.
 *
 * When both extensions exist for the same stem, `.png` wins — rembg's
 * transparent output is the newer source of truth.
 */

import * as fs from "fs";
import * as path from "path";

const ROOT = path.resolve(__dirname, "..");
const DIR = path.join(ROOT, "public", "images", "items");
const OUT = path.join(ROOT, "src", "data", "item-images-map.generated.ts");

const TYPE_SLUG_REVERSE: Record<string, string> = {
  booster: "BOOSTER",
  duopack: "DUOPACK",
  tripack: "TRIPACK",
  blister: "BLISTER",
  "mini-tin": "MINI_TIN",
  "pokeball-tin": "POKEBALL_TIN",
  bundle: "BUNDLE",
  "box-set": "BOX_SET",
  etb: "ETB",
  "booster-box": "BOOSTER_BOX",
  upc: "UPC",
  tin: "TIN",
  "theme-deck": "THEME_DECK",
  "trainer-kit": "TRAINER_KIT",
};

// Ordered list of known type slugs, longest first — the filename parse
// must prefer multi-word slugs (e.g. "booster-box") before single words
// ("booster") so `arceus-booster-box.jpg` doesn't get misclassified as
// `arceus` + `booster-box` ✓ vs `arceus-booster` + `-box`.
const SLUGS_BY_LENGTH = Object.keys(TYPE_SLUG_REVERSE).sort(
  (a, b) => b.length - a.length,
);

function detect(
  file: string,
): { serieSlug: string; type: string; stem: string; ext: "jpg" | "png" } | null {
  let ext: "jpg" | "png";
  let stem: string;
  if (file.endsWith(".jpg")) {
    ext = "jpg";
    stem = file.slice(0, -4);
  } else if (file.endsWith(".png")) {
    ext = "png";
    stem = file.slice(0, -4);
  } else {
    return null;
  }
  for (const typeSlug of SLUGS_BY_LENGTH) {
    const suffix = `-${typeSlug}`;
    if (stem.endsWith(suffix)) {
      return {
        serieSlug: stem.slice(0, -suffix.length),
        type: TYPE_SLUG_REVERSE[typeSlug],
        stem,
        ext,
      };
    }
  }
  return null;
}

const typeMap: Record<string, Set<string>> = {};
// stem → preferred extension (png wins over jpg when both exist)
const extByStem = new Map<string, "jpg" | "png">();

const files = fs.readdirSync(DIR);
for (const file of files) {
  const hit = detect(file);
  if (!hit) continue;
  if (!typeMap[hit.serieSlug]) typeMap[hit.serieSlug] = new Set();
  typeMap[hit.serieSlug].add(hit.type);

  const current = extByStem.get(hit.stem);
  if (!current || (current === "jpg" && hit.ext === "png")) {
    extByStem.set(hit.stem, hit.ext);
  }
}

// Stable output: series sorted alphabetically, types sorted too.
const sortedSeries = Object.keys(typeMap).sort();
const typeEntries = sortedSeries.map((slug) => {
  const types = [...typeMap[slug]].sort();
  return `  "${slug}": [${types.map((t) => `"${t}"`).join(", ")}],`;
});

const sortedStems = [...extByStem.keys()].sort();
const urlEntries = sortedStems.map(
  (stem) => `  "${stem}": "/images/items/${stem}.${extByStem.get(stem)}",`,
);

const totalImages = files.filter(
  (f) => f.endsWith(".jpg") || f.endsWith(".png"),
).length;

const contents = `// AUTO-GENERATED by scripts/generate-item-images-map.ts
// Maps each serie slug to the list of ItemType keys that have a static
// artwork in \`public/images/items/\`, plus a flat stem → URL map that
// records the real extension on disk (png preferred over jpg when both
// exist, since rembg outputs PNG with transparency).
//
// DO NOT EDIT BY HAND. Regenerate with \`npm run gen:item-images-map\`.

export const ITEM_IMAGES_BY_SERIE: Record<string, readonly string[]> = {
${typeEntries.join("\n")}
};

/**
 * Resolve \`\${serieSlug}-\${typeSlug}\` (the filename stem) to its public URL,
 * including the real \`.png\` or \`.jpg\` extension. Returns \`undefined\`
 * when no artwork exists for that combination.
 */
export const ITEM_IMAGE_URL: Record<string, string> = {
${urlEntries.join("\n")}
};
`;

fs.writeFileSync(OUT, contents, "utf8");
console.log(
  `[gen:item-images-map] wrote ${sortedSeries.length} series / ${totalImages} images (${extByStem.size} unique stems) → ${path.relative(ROOT, OUT)}`,
);
